### ISSUE TITLE
scrapper other editorials like elsevier

### ISSUE THREAD

**Issue by sustianovich** [SarthakJShetty/pyResearchInsights#10]
Hi,

I know that Scraper.py script is for Springer- >''The aim of this script is to scrape abstracts, author names and date of publication from Springer"
but is it possible to be changed to Elsevier or other ones?

**Comment by SarthakJShetty** [comment]
It is technically possible, although not supported currently. If you want you can add this functionality and open a PR and I'll review it. The current code is modular enough to support this.
Closing this for now.
