### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by amscosta2022** [SarthakJShetty/pyResearchInsights#11]
Hi 
I just installed the package locally.
However is crashing . Please see the attached image. I think the issue is related to Beautiful Soup.
![Image1](https://github.com/SarthakJShetty/pyResearchInsights/assets/104867129/8a0b0ce4-cde2-438b-afbd-307a5a7c9667)

**Comment by amscosta2022** [comment]
Maybe you could share your working docker image.

**Comment by SarthakJShetty** [comment]
> Maybe you could share your working docker image.

Hey @amscosta2022! Sorry for the delay, but I've finally figured this out. I will build and post a new package in a new hours.

**Comment by SarthakJShetty** [comment]
Thank you for being patient. [v1.60](https://github.com/SarthakJShetty/pyResearchInsights/releases/tag/v_160) release should solve this issue.
