### ISSUE TITLE
V 1.59 not running python 3.7 installed

### ISSUE THREAD

**Issue by amscosta** [SarthakJShetty/pyResearchInsights#12]
Running the below cell locally (after pip installing the 1.6 version):
from pyResearchInsights.common_functions import pre_processing
from pyResearchInsights.Scraper import scraper_main
from pyResearchInsights.Cleaner import cleaner_main
from pyResearchInsights.Analyzer import analyzer_main
from pyResearchInsights.NLP_Engine import nlp_engine_main

Results in : 

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_7884\966294205.py in <module>
----> 1 from pyResearchInsights.common_functions import pre_processing
      2 from pyResearchInsights.Scraper import scraper_main
      3 from pyResearchInsights.Cleaner import cleaner_main
      4 from pyResearchInsights.Analyzer import analyzer_main
      5 from pyResearchInsights.NLP_Engine import nlp_engine_main

d:\pyresearchinsight\pyresearch-env\lib\site-packages\pyResearchInsights\__init__.py in <module>
      2 from pyResearchInsights.Cleaner import cleaner_main
      3 from pyResearchInsights.Analyzer import analyzer_main
----> 4 from pyResearchInsights.NLP_Engine import nlp_engine_main
      5 from pyResearchInsights.common_functions import pre_processing, arguments_parser, end_process
      6 from pyResearchInsights.system_functions import tarballer, rm_original_folder

d:\pyresearchinsight\pyresearch-env\lib\site-packages\pyResearchInsights\NLP_Engine.py in <module>
     27 from pyResearchInsights.Visualizer import visualizer_main
     28 '''Industrial level toolkit for NLP'''
---> 29 import spacy
     30 
     31 import pyLDAvis

d:\pyresearchinsight\pyresearch-env\lib\site-packages\spacy\__init__.py in <module>
      4 
      5 # set library-specific custom warning handling before doing anything else
----> 6 from .errors import setup_default_warnings
      7 
      8 setup_default_warnings()  # noqa: E402

d:\pyresearchinsight\pyresearch-env\lib\site-packages\spacy\errors.py in <module>
      1 import warnings
      2 
----> 3 from .compat import Literal
      4 
      5 

d:\pyresearchinsight\pyresearch-env\lib\site-packages\spacy\compat.py in <module>
      2 import sys
      3 
----> 4 from thinc.util import copy_array
      5 
      6 try:

d:\pyresearchinsight\pyresearch-env\lib\site-packages\thinc\util.py in <module>
     31     from pydantic import ValidationError, create_model  # type: ignore
     32 
---> 33 from wasabi import table  # type: ignore
     34 
     35 from .compat import (

d:\pyresearchinsight\pyresearch-env\lib\site-packages\wasabi\__init__.py in <module>
      1 from .markdown import MarkdownRenderer  # noqa
----> 2 from .printer import Printer  # noqa
      3 from .tables import row, table  # noqa
      4 from .traceback_printer import TracebackPrinter  # noqa
      5 from .util import MESSAGES  # noqa

d:\pyresearchinsight\pyresearch-env\lib\site-packages\wasabi\printer.py in <module>
     17 
     18 
---> 19 class Printer(object):
     20     def __init__(
     21         self,

d:\pyresearchinsight\pyresearch-env\lib\site-packages\wasabi\printer.py in Printer()
    123         spaced: bool = False,
    124         exits: Optional[Union[int, bool]] = None,
--> 125     ) -> Union[str, None, NoReturn]:
    126         """Print an error message.
    127 

D:\Python37\lib\typing.py in inner(*args, **kwds)
    249         except TypeError:
    250             pass  # All real errors (not unhashable args) are raised below.
--> 251         return func(*args, **kwds)
    252     return inner
    253 

D:\Python37\lib\typing.py in __getitem__(self, parameters)
    346                 parameters = (parameters,)
    347             msg = "Union[arg, ...]: each arg must be a type."
--> 348             parameters = tuple(_type_check(p, msg) for p in parameters)
    349             parameters = _remove_dups_flatten(parameters)
    350             if len(parameters) == 1:

D:\Python37\lib\typing.py in <genexpr>(.0)
    346                 parameters = (parameters,)
    347             msg = "Union[arg, ...]: each arg must be a type."
--> 348             parameters = tuple(_type_check(p, msg) for p in parameters)
    349             parameters = _remove_dups_flatten(parameters)
    350             if len(parameters) == 1:

D:\Python37\lib\typing.py in _type_check(arg, msg, is_argument)
    133     if (isinstance(arg, _SpecialForm) and arg is not Any or
    134             arg in (Generic, _Protocol)):
--> 135         raise TypeError(f"Plain {arg} is not valid as type argument")
    136     if isinstance(arg, (type, TypeVar, ForwardRef)):
    137         return arg

TypeError: Plain typing.NoReturn is not valid as type argument

**Comment by amscosta** [comment]
It is version 1.59 installed not 1.60

**Comment by SarthakJShetty** [comment]
Yes that's because the package is not tested with Python 3.7. I can test it and get back to you.

**Comment by amscosta** [comment]
Thanks.

**Comment by SarthakJShetty** [comment]
Since you've managed to run this code with Python3.11, I'm going to go ahead and close this issue.
